version: '3.9'

services:
  vpn:
    image: ghcr.io/wg-easy/wg-easy
    container_name: vpn
    environment:
      - "LANG=pl"
      - "WG_HOST=ravcube.com"
      - "PASSWORD_HASH=${PASSWORD_HASH}"
      - "PORT=51821"
      - "WG_PORT=51820"
      - "WG_DEFAULT_DNS=192.168.0.5,192.168.0.6"
      - "WG_ALLOWED_IPS=0.0.0.0/0, ::/0, 192.168.0.0/24"
    volumes:
      - "/mnt/core_data/docker/etc/wireguard:/etc/wireguard"
    ports:
      - "51820:51820/udp"
      - "83:51821/tcp"
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: always