@Library('jenkins_shared_lib') _

pipeline {
    agent {
        label 'k3s'
    }
    options {
        skipDefaultCheckout();
        timestamps();
        ansiColor('xterm')
    }
    environment {
        DEFAULT_BRANCH = 'master'
        CREDITS_ID = 'github-token'
    }
    stages {
        stage('Init ENV') {
            steps {
                script {
                    initEnv()
                }
            }
        }

        stage('Configure Triggers') {
            steps {
                script {
                    configureTriggers()
                }
            }
        }

        stage('Checkout') {
            parallel {
                stage('Checkout PR') {
                    when { expression { isPullRequestBuild() } }
                    steps {
                        checkoutPullRequest()
                    }
                }

                stage('Checkout Manual') {
                    when { not { expression { isPullRequestBuild() } } }
                    steps {
                        checkoutBranch("*/${env.DEFAULT_BRANCH}")
                    }
                }
            }
        }

        stage('Init') {
            parallel {
                stage('Init Pipeline Status') {
                    when { expression { isPullRequestBuild() } }
                    steps {
                        script {
                            githubWebhook('PENDING', 'Pipeline started')
                        }
                    }
                }
                stage('Init Submodules') {
                    steps {
                        script {
                            initSubmodules()
                        }
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh '''
                        bash ./docker/validate_docker.sh
                    '''
                }
            }
        }
    }
    post {
        success {
            script {
                githubWebhook('SUCCESS', 'All stages passed ✅')
            }
        }
        failure {
            script {
                githubWebhook('FAILURE', 'Pipeline failed ❌')
            }
        }
    }
}